### ISSUE TITLE
Resizing textareas with dynamically inserted content

### ISSUE THREAD

**Issue by brandondurham** [azoff/AutoResize#2]
I have approximately five textareas on the page that are all updated dynamically with varying content. I see you have a change event built into the plugin, but the textareas aren't resizing when I update their text using the following code: `$('#description').val(contentVariable)`

Am I doing something wrong?

I appreciate any help I can get.

**Comment by azoff** [comment]
Hey Brandon,

Currently, there is no way to programmatically tell AutoResize to resize the textarea. However, if you simulate a keyup event, it should have the same effect:

``` javascript
$('#description').val(contentVariable).trigger('keyup');
```

It's not pretty, but it'll work

**Comment by brandondurham** [comment]
Fabulous. Thank you so much for the quick response.
